### ISSUE TITLE
麻烦提供jmccc -2.5 -SNAPS配套使用的jmccc-yggdrasil-authenticator下载地址

### ISSUE THREAD

**Issue by Eerobrine** [xfl03/JMCCC#31]
无法使用jmccc-yggdrasil-authenticator-2.5beta1与jmccc -2.5 -SNAPS配套

**Comment by xfl03** [comment]
https://s01.oss.sonatype.org/content/repositories/snapshots/dev/3-3/jmccc-yggdrasil-authenticator/3.0-SNAPSHOT/jmccc-yggdrasil-authenticator-3.0-20230130.103353-1.jar
