### ISSUE TITLE
Microsoft authenication support

### ISSUE THREAD

**Issue by eternity4450** [xfl03/JMCCC#34]
Hi! Is Microsoft authentication planned?

**Comment by xfl03** [comment]
I will try to support it.

**Comment by xfl03** [comment]
https://github.com/xfl03/JMCCC/commit/ce2f2fa1db1c5a5aeebe59027d51bb12553ea05b

I have make a simple support of it, you can have a try with version `3.1.0-SNAPSHOT`.

**Comment by xfl03** [comment]
3.1.0 has been released

**Comment by eternity4450** [comment]
Wow, thanks for the quick implementation. I will definitely try and give feedback.
